### ISSUE TITLE
[Bug] The snippets do not work 

### ISSUE THREAD

**Issue by gusbemacbe** [idleberg/vscode-emoji-code#11]
Hi!

* I installed via the command `ext install idleberg.emoji-code`. 
* I use Manjaro Linux 18.0.3 Illyria and VSCode Insiders 1.32.0. 
* I have already enabled `"editor.quickSuggestions":true`

I tried to type the abbreviations and the `ji:*` do not show up. Both in HTML and Markdown. I also read "Visual Studio Code supports fuzzy completion" and tried to correct the abbreviations, but nothing worked.

**Comment by idleberg** [comment]
Could you please try the following:

1. Run the `Extensions: Open Extensions Folder` command in VSCode
2. Open the folder for this extension (`idleberg.emoji-code-<SEMVER>` - where `<SEMVER>` is the version)
3. Is there a `node_modules` folder?

If not, it looks like Microsoft has changed something in the installing process for extensions.

Quick fix:

Run `npm install` in the `idleberg.emoji-code-<SEMVER>` folder.

**Comment by gusbemacbe** [comment]
Hello @idleberg !

> 3\. Is there a `node_modules` folder?

No. 

> Run `npm install` in the `idleberg.emoji-code-<SEMVER>` folder.

It worked now. Then it is because of `node_modules`. Does the extension installed from VSCode or .vsix not come with _node_modules`?

**Comment by idleberg** [comment]
It appears that VSCode only installs Node modules when they're used in the actual extension. This extension was supposed to build those snippets at install-time, but that stopped working in some version of VSCode.

Anyway, it should be fixed in v0.7.4. Thanks for reporting the issue!

**Comment by gusbemacbe** [comment]
Hi @idleberg !

I have tested the latest version, but it did not pre-build. Then I have to install again via npm.

**Comment by carlocardella** [comment]
hello, I can still repro with v0.7.4 both on Mac and Windows
