### ISSUE TITLE
Deprioritize emoji

### ISSUE THREAD

**Issue by minj** [idleberg/vscode-emoji-code#12]
Any way to deprioritize the suggestions in autocomplete?

There are so many results that they are bound to overwhelm any code symbols with fuzzy matching.

These leads time wasting trying to select code symbols instead of emoji

**Comment by trepichio** [comment]
I'm facing same issue. If anyone knows a workaround please let me know.

**Comment by idleberg** [comment]
> By default, VS Code shows snippets and completion proposals in one widget. You can control the behavior with the `editor.snippetSuggestions` setting. 

https://code.visualstudio.com/docs/editor/intellisense#_snippets-in-suggestions
